/**
 * Scrum Poker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Room } from '../model/models';
import { RoomsPostRequest } from '../model/models';
import { RoomsRoomIdEstimatesPutRequest } from '../model/models';
import { RoomsRoomIdPatchRequest } from '../model/models';
import { RoomsRoomIdPlayersPostRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new room
     * 
     * @param roomsPostRequest 
     */
    roomsPost(roomsPostRequest: RoomsPostRequest, extraHttpRequestParams?: any): Observable<Room>;

    /**
     * Submit an estimate
     * 
     * @param roomId 
     * @param roomsRoomIdEstimatesPutRequest 
     */
    roomsRoomIdEstimatesPut(roomId: string, roomsRoomIdEstimatesPutRequest: RoomsRoomIdEstimatesPutRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get room information
     * 
     * @param roomId 
     */
    roomsRoomIdGet(roomId: string, extraHttpRequestParams?: any): Observable<Room>;

    /**
     * Reveal or reset the board
     * Use this to flip cards (reveal) or clear estimates (reset)
     * @param roomId 
     * @param roomsRoomIdPatchRequest 
     */
    roomsRoomIdPatch(roomId: string, roomsRoomIdPatchRequest: RoomsRoomIdPatchRequest, extraHttpRequestParams?: any): Observable<Room>;

    /**
     * Join a room
     * Add a new player to a room. If the player already exists, it does nothing.
     * @param roomId 
     * @param roomsRoomIdPlayersPostRequest 
     */
    roomsRoomIdPlayersPost(roomId: string, roomsRoomIdPlayersPostRequest: RoomsRoomIdPlayersPostRequest, extraHttpRequestParams?: any): Observable<{}>;

}
