/**
 * Scrum Poker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoomsRoomIdPatchRequest { 
    action: RoomsRoomIdPatchRequest.ActionEnum;
}
export namespace RoomsRoomIdPatchRequest {
    export const ActionEnum = {
        Reveal: 'reveal',
        Reset: 'reset'
    } as const;
    export type ActionEnum = typeof ActionEnum[keyof typeof ActionEnum];
}


