/**
 * Scrum Poker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Player } from './player';


export interface Room { 
    id?: string;
    name?: string;
    host?: string;
    revealed?: boolean;
    players?: Array<Player>;
}

