/**
 * Scrum Poker API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Player } from './player';


export interface RoomsPostRequest { 
    /**
     * Optional display name of the room
     */
    name: string;
    /**
     * Player creating the room
     */
    player?: Player;
}

